name: Check homework
on: [push]
jobs:
  runner-job:
    runs-on: ubuntu-latest
    env:
      IMAGE: 'ktshub/backend-summer-2021:task-6a4c4c31-536f-4469-8f72-e15ba616d4a8'
      CONFIGPATH: /go/code/source/tests/config.yml
      PYTHONPATH: /go/code/source
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: update pythonpath
        run: echo "PYTHONPATH=$PYTHONPATH:/home/runner/work/hw-backend-summer-2021-3-db_gino/hw-backend-summer-2021-3-db_gino" >> $GITHUB_ENV

      - name: set CONFIGPATH
        run: echo "CONFIGPATH=/home/runner/work/hw-backend-summer-2021-3-db_gino/hw-backend-summer-2021-3-db_gino/tests/config.yml" >> $GITHUB_ENV

      - name: handle migrations
        run:  alembic upgrade head

      - run: docker run --entrypoint /bin/bash -e GITHUB_REPOSITORY -e GITHUB_REF -e CONFIGPATH=${{ env.CONFIGPATH }} -e PYTHONPATH=${{ env.PYTHONPATH }} --network host --mount src="$(pwd)",target=/go/code/source,type=bind ${{ env.IMAGE }} -c "mv build/main source && ls -lah && cd source && ./main"

